### ISSUE TITLE
Sometimes random apps show up in the widgets page

### ISSUE THREAD

**Issue by kaaslikker2** [LaughingQuoll/NCXI#14]
iPhone 6s+ iOS 10.2

**Comment by LaughingQuoll** [comment]
Screenshot please.

**Comment by kaaslikker2** [comment]
http://imgur.com/AE2zwgT
http://imgur.com/9JlgfDq

**Comment by kaaslikker2** [comment]
When sliding to the widgets page a random app shows up but you cannot interact with it

**Comment by LaughingQuoll** [comment]
Should be resolved as of #34d6224
