### ISSUE TITLE
Notifications Problem 

### ISSUE THREAD

**Issue by zyan910** [LaughingQuoll/NCXI#18]
It's not letting me scroll down
[IMG_1646.zip](https://github.com/LaughingQuoll/NCXI/files/1347101/IMG_1646.zip)
 my notifications when there's 1 or 2 notifications below

**Comment by LaughingQuoll** [comment]
Oh I think I know what the issue is. i'll fix it soon.

**Comment by LaughingQuoll** [comment]
Resolved
