### ISSUE TITLE
Swiping right

### ISSUE THREAD

**Issue by a-sgg** [LaughingQuoll/NCXI#20]
https://imgur.com/XFBn1b2

Cannot clear notifications individually
Swiping up overlaps with the date (a little bit)
And I don't know if the (don't know how to explain)is a bug or intentional

**Comment by a-sgg** [comment]
I can clear notifs when it's only one. But if it's 2 or more I can't

**Comment by a-sgg** [comment]
Oh jeez, ignore the clearing notifs one. Must be a tweak of mine. Dang

**Comment by LaughingQuoll** [comment]
So is this an issue or not?
