### ISSUE TITLE
Spotlight and 3d touch issue

### ISSUE THREAD

**Issue by jedlas012** [LaughingQuoll/NCXI#5]
When swiping to the spotlight on NC, the date overlaps each other. And when you 3D touch a notification, nothing happens and it just turns invisible.

https://imgur.com/gallery/Wz6cy

Device Info: iPhone 6s running iOS 10.2

All my tweaks doesn't interfere with the notification center.

**Comment by LaughingQuoll** [comment]
Should be fixed in #34d6224
