### ISSUE TITLE
NCXI Settings blank

### ISSUE THREAD

**Issue by Zer0Degree** [LaughingQuoll/NCXI#7]
Under settings>eleven>NCXI no content are displayed.

**Comment by Zer0Degree** [comment]
iPhone SE iOS 10.2

**Comment by zyan910** [comment]
What option would be there to configure??

**Comment by Zer0Degree** [comment]
You mean what am I expected to see in it ?

**Comment by zyan910** [comment]
Yeah...i dont think there r any options to configure....

**Comment by Zer0Degree** [comment]
Ooooook that makes sence...

**Comment by LaughingQuoll** [comment]
As of now there are no options to configure.
